### ISSUE TITLE
Version 1.1.1 published artifact has no classes

### ISSUE THREAD

**Issue by mikedawson** [robertlevonyan/composable-button-toggle-group#1]
Hi,

Version 1.1.1 published on maven central has no classes in the AAR:

https://search.maven.org/artifact/com.robertlevonyan.compose/buttontogglegroup/1.1.1/aar

Seems like something went wrong. As there are no classes, this artifact doesn't provide any composable functions.

**Comment by robertlevonyan** [comment]
Hi. Please try the version 1.1.2
